server:
  port: 5000
  shutdown: graceful

spring:
  main:
    banner-mode: off

  application:
    name: mini-banking-server

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/mini-banking-db
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
    username: ${DB_USERNAME:mini-banking-user}
    password: ${DB_PASSWORD:P2LHrNj4RcNwqY}

  lifecycle:
    timeout-per-shutdown-phase: 30s

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: ${JWT_SECRET:Zh28h8kvun73MrRyY82fwR3FXMvBUTpd}
  expiration: ${JWT_EXPIRATION:3600000}
